server:
  port: 8012
spring:
  cloud:
    stream:
      bindings:
        output:
          desination: bookChangeTopic
          content-type: application/json
      kafka:
        binder:
          brokers: localhost
