server:
  port: 8013
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8020/auth/user
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: output
          content-type: application/json
          group: writer-group
      kafka:
        binder:
          brokers: localhost
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:8014
redis:
  host: 192.168.99.100
  port: 6379