spring:
  datasource:
    driverClassName: org.h2.Driver
    url: 'jdbc:h2:mem:bookDb'
    username: sa
    password: "{cipher}c24175513bec59f8ccf7d45ff71bd6b3464206748327a5ee9dd04e1199581e12"
  h2:
    console:
      enabled: true
      path: /h2console
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: validate